### ISSUE TITLE
Add Years 2010-2012

### ISSUE THREAD

**Issue by href** [interactivethings/swiss-maps#21]
Do you have any way of adding the years 2010-2012? From what I understand the VECTOR200 data is missing so those years can't be built. I had a look around the swisstopo website and I couldn't find any such data. In fact the VECTOR200 data seems to be rather pricey? How did you manage to add them to this repo in the first place? :)

I'm also interested in adding the 2016 data, so if you could illuminate how you got your data before I might be able to send a pull request your way with the latest records once they are released.

Thanks!

**Comment by herrstucki** [comment]
I have swissBOUNDARIES3D data going back to 2010 in this repo. I removed it from the build because they don't contain lakes and can't be properly combined with the VEC200 lakes (see discussion in #11). If you only need boundaries without lakes, you can use that data.

The 2016 data isn't published yet by swisstopo (it always takes them a while, it's usually published around Feb/Mar). My process of getting it: I download it for free from http://www.toposhop.admin.ch/de/shop/products/landscape/swissBoundaries3D_1 each year and keep it here. swisstopo only makes the latest version available, so this is the only place you can get the past years without asking swisstopo. The swissBOUNDARIES3D also contains the VEC200 _administrative boundaries_ (the expensive VECTOR200 dataset contains much more); that's what is used here to build the TopoJSON files.

Now, if you want the older VEC200 boundaries, you could ask swisstopo directly. If you get them, it would be very cool if you could add them to this repo :grin:

**Comment by href** [comment]
I contacted them already about the 2016 data and I'll talk to them about the historic data as well. We will actually need the 2017 data on or before January 1st 2017 for our product which will be live by that time, so we have to find some way to get Swisstopo to be quicker :)

Since you're not using any magic methods or hidden urls I'll talk to Swisstopo and post my findings here.

**Comment by herrstucki** [comment]
Thanks, looking forward to your update!

**Comment by href** [comment]
I already found out that 2016 is going to be released in mid-february. So there's that.

Getting more info about timely updates and more years will take a few months probably. If all goes well we're going to have a meeting with Swisstopo and some representative of the canton of Zug where we can make our points. Our goal is to improve this situation by the end of 2016.

But yeah, this is not going to be resolved quickly :)
